import Head from 'next/head'
import Image from 'next/image'
import img from '../public/images/fondo.png'
import logo from '../public/images/logo-oceanit.png'
import boton1 from '../public/images/boton_1.png'
import boton2 from '../public/images/boton_2.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Oceanit - Próximamente</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='grid items-center justify-center w-screen h-screen' style={{
        backgroundColor: '#0041c0',
        backgroundImage: `url(${img.src})`,
        backgroundSize: 'cover',
      }}>
        <div className='mx-auto mx-9'>
          <Image
            src={logo}
            alt='logo'
            placeholder='blur'
            priority
          />
          <div>
            <h1 className='text-4xl sm:text-6xl text-center text-white'>Próximamente</h1>
          </div>
          <div className='flex justify-between items-center m-5'>

            <div className='mr-2'>
              <Image
                src={boton1}
                alt='boton app'
                placeholder='blur'
                priority
              />
            </div>

            <div className='ml-2'>
              <Image
                src={boton2}
                alt='boton app'
                placeholder='blur'
                priority
              />
            </div>

          </div>
        </div>


      </main>
    </div>
  )
}
