import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Masthead from "../components/masthead";
import AboutUs from "../components/aboutus";
import FooterMain from "../components/FooterMain";
import Techs from "../components/Techs";
import Skills from "../components/skills";
import Works from "../components/works";
import Nav from "../components/navbar";
import ContactUs from "../components/contactus";

export default function Home() {
  return (
    <div>
      <Head>
        <title>OceanIT Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main>
        <Masthead />
        <AboutUs />
        <Skills />
        <Works />
        <Techs />
        <ContactUs />
      </main>
      <FooterMain />
    </div>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}
